namespace InputData.Map;

table PlatformState {
	id:ubyte;
	platform_state:ubyte;
}

table SpawnerInfo{
	spawn_item_id:ushort;
	spawn_item_index:ubyte;
	spawn_point_index:ubyte;
}

table StartEndGameInfo{
	map_index:ubyte;
	p1_life:ubyte;
	p2_life:ubyte;
	game_end:ubyte;
	game_winner:string;
}

union MapMessageType{
	platform_state:PlatformState,
	spawner_info:SpawnerInfo,
	start_end_game_info:StartEndGameInfo,
}

table MapMessage{
	map_message_type:MapMessageType;
}

file_identifier "MAPP";
root_type MapMessage;