namespace InputData.Map;

table PlatformState {
	id:ubyte;
	platform_state:ubyte;
}

table SpawnerInfo{
	spawn_item_id:ushort;
	spawn_item_index:ubyte;
	spawn_point_index:ubyte;
}

table StartEndGameInfo{
	map_index:ubyte;
	game_end:ubyte;
	game_winner:string;
}

table CurrentGameInfo{
	time:ubyte;
	player_life:ubyte;
	player_name:string;
}

union MapMessageType{
	platform_state:PlatformState,
	spawner_info:SpawnerInfo,
	start_end_game_info:StartEndGameInfo,
	current_game_info:CurrentGameInfo
}

table MapMessage{
	map_message_type:MapMessageType;
}

file_identifier "MAPP";
root_type MapMessage;